#!/bin/sh

IFS=''
# This is the old and simple code, which we can't grep, unfortunately
#wdiff \
#    --start-delete=`tput setaf 1; tput bold` \
#    --end-delete=`tput sgr0` \
#    --start-insert=`tput setaf 2; tput bold` \
#    --end-insert=`tput sgr0` \
#    $@

if [ "$IS_GIT_DIFF" ]; then
    echo $'\e[1;34m'"$1 => $2"$'\e[0m'
fi

start_insert=$'\ei'
end_insert=$'\eI'
start_delete=$'\ed'
end_delete=$'\eD'

wdiff --avoid-wraps \
    --start-insert="$start_insert" --end-insert="$end_insert" \
    --start-delete="$start_delete" --end-delete="$end_delete" \
    $@ |
    grep -P --context=2 \
        "($start_insert|$end_insert|$start_delete|$end_delete)" |
    sed "s,$start_insert,"$'\e[32m',g |
    sed "s,$end_insert,"$'\e[0m',g |
    sed "s,$start_delete,"$'\e[31m',g |
    sed "s,$end_delete,"$'\e[0m',g |
    cat
